### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by jonashaag** [mystor/gh-release-watch#9]
```
e.ConfigError {message: "Login service configuration not yet loaded"}message: "Login service configuration not yet loaded"stack: (...)__proto__: Error
    at http://gh-release-watch.com/674074566b0b2460b01dd007d9ea034bd5ec560d.js:11:3481
    at http://gh-release-watch.com/674074566b0b2460b01dd007d9ea034bd5ec560d.js:11:3557
    at http://gh-release-watch.com/674074566b0b2460b01dd007d9ea034bd5ec560d.js:11:3668
```

This is what happens when I click Login.

**Comment by mystor** [comment]
The login configuration seems to work correctly for me - can you try it again and see if the problem persists?

**Comment by jonashaag** [comment]
Still doesn't work (latest Chrome and FF). It works in Safari though. The popup doesn't open in Chrome and FF.

**Comment by jonashaag** [comment]
Still not fixed.
